language: node_js
node_js:
  - "10"
script:
  - npm run test-ci
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test-local; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test-ci; fi'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install pg
